title: slashbin
email: prakash.binoy@gmail.com
description: Binoy Michael Prakash's personal website
url: "http://slashbin.in" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [vendor]

sass:
    style: compressed
